name: Deploy AutoMember to Azure Web App (SP)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Zip app for deploy
        run: zip -r release.zip . -x "*.git*" "data/*" "*.sqlite"

      - name: Azure login (Service Principal)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy zip to Web App
        uses: azure/cli@v2
        with:
          inlineScript: |
            az webapp deploy \
              --resource-group "${{ secrets.AZURE_RESOURCE_GROUP }}" \
              --name "${{ secrets.AZURE_WEBAPP_NAME }}" \
              --type zip \
              --src-path release.zip
